Dynamic thread pool
vostok/hosting pull request #39
Opened 2021-01-20 05:18 UTC by HolyPrapor

2021-01-22 08:44 UTC, KungA commented on Vostok.Hosting/Helpers/IVostokHostingEnvironmentExtensions.cs
> +    public static class IVostokHostingEnvironmentExtensions
Это что такое и зачем?

2021-01-22 08:49 UTC, KungA commented on Vostok.Hosting/Setup/IVostokHostingEnvironmentBuilder.cs
> +        IVostokHostingEnvironmentBuilder SetupThreadPoolMultiplier(int multiplier);
А где `dynamic thread pool configuration from app settings`?

Должна быть перегрузка использующая IVostokHostingEnvironmentSetupContext.

2021-01-22 17:11 UTC, HolyPrapor commented on Vostok.Hosting/Setup/IVostokHostingEnvironmentBuilder.cs
> +        IVostokHostingEnvironmentBuilder SetupThreadPoolMultiplier(int multiplier);
Там не получится так просто добавить поддержку изменения тредпула через настройки во время создания окружения, поскольку источник настроек может задаваться на этапе инициализации (о таком способе даже сказано в гайде), а не во время создания окружения.


Можно добавить метод, о котором ты говоришь, но тогда не будет способа динамически конфигурировать тредпул, если я хочу источник настроек указать на этапе инициализации.

2021-01-22 17:18 UTC, HolyPrapor commented on Vostok.Hosting/Setup/IVostokHostingEnvironmentBuilder.cs
> +        IVostokHostingEnvironmentBuilder SetupThreadPoolMultiplier(int multiplier);
Поэтому здесь есть 3 варианта:

1) Усложнять логику работы каким-то образом так, чтобы я мог пытаться подписаться на изменения настроек и переконфигурировать тредпул после инициализации. (Причем, на самом деле, метод добавления нового источника настроек доступен и в `RunAsync`, и в случае, если пользователь вдруг использует его там, не получится подписаться на изменения совсем)

2) Вытащить экстеншн из `IVostokHostingEnvironment`, чтобы пользователь мог сам когда ему удобно переконфигурировать тредпул. (Что я и сделал)

3) Забить на случай инициализации, сделать как ты предлагаешь, и сообщить пользователю о том, что в таком случае конфигурирование тредпула пусть реализует самостоятельно. (Либо насильно заставить конфигурировать источники настроек до инициализации)

2021-01-25 11:19 UTC, KungA commented on Vostok.Hosting/Setup/IVostokHostingEnvironmentBuilder.cs
> +        IVostokHostingEnvironmentBuilder SetupThreadPoolMultiplier(int multiplier);
После небольшого обсуждения с @iloktionov по задаче у меня сложилось впечатление что в ней нужно:

- добавить Func<IConfigurationProvider, ThreadPoolSettings> в VostokHostSettings
- либо сделать как-то более умно, например считать, что этот Func можно получить используя ConfigurationProvider.Get<ThreadPoolSettings> (чтобы иметь возможность подписаться на обсервабл, а не пуллить настройки из фанка каждые 10 секунд

Правда без первого варианта мы не сможем следить за горячими лимитами (если они меняются то тредпул тоже нужно переконфигурировать).

2021-02-01 08:12 UTC, HolyPrapor commented on Vostok.Hosting/Setup/IVostokHostingEnvironmentBuilder.cs
> +        IVostokHostingEnvironmentBuilder SetupThreadPoolMultiplier(int multiplier);
Так как горячие лимиты задаются провайдерами, то за ними можно следить только периодическим пуллом настроек.

Поэтому я дал способ прокинуть Func, о котором ты говорил, через `IVostokHostingEnvironmentBuilder`.

Статическую конфигурацию тредпула сместил из `VostokHost` в `EnvironmentBuilder` (Думаю, что она изначально должна была быть там).

2021-02-01 08:24 UTC, HolyPrapor commented on Vostok.Hosting/Setup/IVostokHostingEnvironmentBuilder.cs
> +        IVostokHostingEnvironmentBuilder SetupThreadPoolMultiplier(int multiplier);
Не добавил Func в `VostokHostSettings`, нужно?

2021-02-01 08:41 UTC, KungA commented on Vostok.Hosting/Setup/IVostokHostingEnvironmentBuilder.cs
> +        IVostokHostingEnvironmentBuilder SetupThreadPoolMultiplier(int multiplier);
Да, а добавлять знания про тредпул в IVostokHostingEnvironmentBuilder вообще не нужно.

2021-02-01 08:49 UTC, HolyPrapor commented on Vostok.Hosting/Setup/IVostokHostingEnvironmentBuilder.cs
> +        IVostokHostingEnvironmentBuilder SetupThreadPoolMultiplier(int multiplier);
Ты имеешь в виду статический тредпул, или и динамический тоже?

Уберу, но не вижу, для чего это нужно

2021-02-01 09:02 UTC, KungA commented on Vostok.Hosting/Setup/IVostokHostingEnvironmentBuilder.cs
> +        IVostokHostingEnvironmentBuilder SetupThreadPoolMultiplier(int multiplier);
Потому что это раньше было настройкой хоста, и ей же должно остаться.

Например, так несколько запущенных приложений точно не будут "воевать" за тредпул.

2021-02-03 06:55 UTC, HolyPrapor commented on Vostok.Hosting/Setup/IVostokHostingEnvironmentBuilder.cs
> +        IVostokHostingEnvironmentBuilder SetupThreadPoolMultiplier(int multiplier);
Done.

2021-02-04 11:42 UTC, KungA commented on Vostok.Hosting/Components/Environment/EnvironmentBuilder.cs
> +        private readonly DynamicThreadPoolBuilder dynamicThreadPoolBuilder;
Вроде мы решили всю работу с тредпулом делать на уровне хоста?

2021-02-08 08:13 UTC, HolyPrapor commented on Vostok.Hosting/Components/Environment/EnvironmentBuilder.cs
> +        private readonly DynamicThreadPoolBuilder dynamicThreadPoolBuilder;
Я подумал, что ты конкретно про публичный интерфейс

На этот раз перенес всё в хост.

2021-02-09 14:48 UTC, KungA requested changes

2021-02-09 14:48 UTC, KungA commented on Vostok.Hosting/Components/ThreadPool/ThreadPoolSettings.cs
> +        internal float? CpuUnits { get; set; }
А зачем это тут, если мы будем использовать всегда IVostokApplicationLimits.CpuUnits?

2021-02-09 14:48 UTC, KungA commented on Vostok.Hosting/Components/ThreadPool/DynamicThreadPoolSettings.cs
> +        public TimeSpan ChecksPeriod = 10.Seconds();
Смысл двух классов настроек не очень понятен, почему бы не считать ChecksPeriod тоже горячим?

2021-02-09 14:48 UTC, KungA commented on Vostok.Hosting/VostokHost.cs
> +            using (dynamicThreadPool)
Может стоит диспоузить его до остального окружения?

2021-02-09 14:48 UTC, KungA commented on Vostok.Hosting/Components/ThreadPool/DynamicThreadPoolSettings.cs
> +        public Func<IConfigurationProvider, ThreadPoolSettings> ThreadPoolSettingsProvider { get; set; }
Насколько я понял этот класс, то без этого провайдера все сеттинги не имеют смысла, поэтому логичней инициализировать его в конструкторе.

2021-02-09 14:48 UTC, KungA commented on Vostok.Hosting/VostokHostSettings.cs
> +        public DynamicThreadPoolSettings DynamicThreadPoolSettings { get; set; }
Лучше прямо тут 

`Func<IConfigurationProvider, ThreadPoolSettings> ThreadPoolSettingsProvider { get; set; }`

2021-02-09 14:48 UTC, KungA commented on Vostok.Hosting/Components/ThreadPool/DynamicThreadPoolTracker.cs
> +        public void LaunchPeriodicalChecks(CancellationToken externalToken)
Мы же явно диспоузим его, зачем тут собирать LinkedTokenSource?

2021-02-09 14:48 UTC, KungA commented on Vostok.Hosting/Components/ThreadPool/DynamicThreadPoolTracker.cs
> +        public void LaunchPeriodicalChecks(CancellationToken externalToken)
Метод нельзя вызвать 2 раза, может тогда сразу из конструктора запустим (тогда и Interlocked не нужен)?

2021-02-09 14:48 UTC, KungA commented on Vostok.Hosting/Components/ThreadPool/DynamicThreadPoolTracker.cs
> +                ThreadPoolUtility.Setup(settings.ThreadPoolMultiplier, settings.CpuUnits.Value);
Наверно лимита может не быть?

2021-02-09 14:48 UTC, KungA commented on Vostok.Hosting/Components/ThreadPool/DynamicThreadPoolTracker.cs
> +                currentSettings.CpuUnits = applicationLimits.CpuUnits;
Не помню что внутри, но точно ли обновляется именно поле CpuUnits, а не вся моделька environment.Limits?

2021-02-09 14:48 UTC, KungA commented on Vostok.Hosting/Components/ThreadPool/DynamicThreadPoolTracker.cs
> +                await Task.Delay(checkPeriod, cancellationToken).ConfigureAwait(false);
Стоит запретить указывать checkPeriod = 0.

2021-02-09 14:48 UTC, KungA commented on Vostok.Hosting/Components/ThreadPool/DynamicThreadPoolTracker.cs
> +            try
Лучше оборачивать не TryGetThreadPoolSettings, а сразу всю итерацию (если упадёт SetupThreadPool, то весь цикл умрёт).

2021-02-09 14:48 UTC, KungA commented on Vostok.Hosting/Components/ThreadPool/DynamicThreadPoolSettings.cs
> +        public TimeSpan ChecksPeriod = 10.Seconds();
Да и вообще можно не давать пользователю менять его (зачем ему это нужно?).

2021-02-09 14:48 UTC, KungA commented on Vostok.Hosting/Components/ThreadPool/DynamicThreadPoolTracker.cs
> +                settings.CpuUnits.HasValue ? $"{settings.CpuUnits.Value:F2} core(s)" : "<unlimited>");
Вот и случай unlimited нашелся. Помнится раньше мы брали ProcessCount вместо него?

2021-02-09 14:56 UTC, HolyPrapor commented on Vostok.Hosting/Components/ThreadPool/ThreadPoolSettings.cs
> +        internal float? CpuUnits { get; set; }
Вообще для двух целей:
1. Чтобы закэшировать в трекере, и иметь возможность сравнить новые настройки с настройками на прошлом итерации
2. Чтобы пользователю было понятнее, как формируется новое значение тредпула

Может быть можно и убрать, но всё равно новый класс придётся заводить с этим значением чтобы запомнить предыдущее значение настроек, хз как лучше

2021-02-09 14:57 UTC, HolyPrapor commented on Vostok.Hosting/Components/ThreadPool/DynamicThreadPoolSettings.cs
> +        public TimeSpan ChecksPeriod = 10.Seconds();
Наверное можно и убрать, 10 секунд должно быть всегда достаточно

2021-02-09 14:58 UTC, HolyPrapor commented on Vostok.Hosting/Components/ThreadPool/DynamicThreadPoolTracker.cs
> +        public void LaunchPeriodicalChecks(CancellationToken externalToken)
Я думал мб будет полезно иногда выключить динамическую конфигурацию, но наверное это тоже не нужно

2021-02-09 14:59 UTC, HolyPrapor commented on Vostok.Hosting/Components/ThreadPool/DynamicThreadPoolTracker.cs
> +                currentSettings.CpuUnits = applicationLimits.CpuUnits;
Да

2021-02-09 15:03 UTC, HolyPrapor commented on Vostok.Hosting/Components/ThreadPool/DynamicThreadPoolTracker.cs
> +                settings.CpuUnits.HasValue ? $"{settings.CpuUnits.Value:F2} core(s)" : "<unlimited>");
Вообще логгинг ApplicationLimits сделан идентично

Если ты про unlimited значение, то этот случай в `ThreadPoolUtility.Setup()` внутри обрабатывается

2021-02-09 15:09 UTC, KungA commented on Vostok.Hosting/Components/ThreadPool/ThreadPoolSettings.cs
> +        internal float? CpuUnits { get; set; }
Я бы сказал наоборот, показываешь пользователю поле, которое он не может прочитать/поменять.

А для внутренних целей заведи просто поляшку `float?`, городить классы не обязательно.

2021-02-09 15:16 UTC, KungA commented on Vostok.Hosting/Components/ThreadPool/DynamicThreadPoolTracker.cs
> +                settings.CpuUnits.HasValue ? $"{settings.CpuUnits.Value:F2} core(s)" : "<unlimited>");
Я скорее да, про

https://github.com/vostok/hosting/pull/39/files#r572938765

и возможный nullref.

2021-02-25 20:14 UTC, KungA commented on Vostok.Hosting/Components/ThreadPool/ThreadPoolSettings.cs
> +        public ThreadPoolSettings(int threadPoolMultiplier = 32)
1. конструктор можно убрать, и оставить только поле
2. константа 32 есть уже в двух местах, либо в константу, либо ещё куда-то деть

2021-02-25 20:16 UTC, KungA commented on Vostok.Hosting/Components/ThreadPool/DynamicThreadPoolTracker.cs
> +            return !previousThreadPoolMultiplier.HasValue ||
просто previousThreadPoolMultiplier != newThreadPoolMultiplier вроде тоже самое делает

2021-02-25 20:18 UTC, KungA commented on Vostok.Hosting/VostokHostSettings.cs
> +        public Func<IConfigurationProvider, ThreadPoolSettings> ThreadPoolSettingsProvider { get; set; }
[CanBeNull]

2021-02-25 20:20 UTC, KungA commented on Vostok.Hosting/Components/ThreadPool/DynamicThreadPoolTracker.cs
> +            if (cpuUnits.HasValue)
а без ифов не выйдет случайно?) 
ThreadPoolUtility.Setup(threadPoolMultiplier, cpuUnits);

2021-02-25 20:21 UTC, KungA approved these changes
1. конструктор можно убрать, и оставить только поле
2. константа 32 есть уже в двух местах, либо в константу, либо ещё куда-то деть

2021-03-08 12:57 UTC, merged