Dispose leaks
vostok/hosting pull request #66
Opened 2021-10-01 08:51 UTC by HolyPrapor

2021-10-01 08:52 UTC, HolyPrapor commented on Vostok.Hosting/Components/SystemMetrics/SystemMetricsBuilder.cs
> +                context.DisposableHostExtensions.Add(collector.ReportMetrics(metricContext, settings.ProcessMetricsReportingPeriod));
These lines will result in "Dispose of `CurrentProcessMetricsCollector` component..." in logs.
I don't think that's a problem though...

2021-10-01 13:04 UTC, KungA requested changes

2021-10-01 13:04 UTC, kungasc commented on Vostok.Hosting/Components/Diagnostics/DiagnosticInfo.cs
> +        {
не понятно, зачем такой диспоуз

пусть за диспоуз будут ответственны те, кто взял провайдера

2021-10-01 13:04 UTC, kungasc commented on Vostok.Hosting/Components/Diagnostics/HealthTracker.cs
> +            foreach (var check in checks.Values.OfType<IDisposable>())
аналогично

2021-10-01 13:04 UTC, KungA commented on Vostok.Hosting/Components/SystemMetrics/SystemMetricsBuilder.cs
> +                context.DisposableHostExtensions.Add(collector.ReportMetrics(metricContext, settings.ProcessMetricsReportingPeriod));
если этой штуки раньше не было в HostExtensions то только ради диспоуза лучше и не мусорить

2021-10-01 13:04 UTC, KungA commented on Vostok.Hosting/Components/SystemMetrics/SystemMetricsBuilder.cs
>                  context.DisposableHostExtensions.Add(gcMonitor.ReportMetrics(metricContext));
тоже подозрительно

2021-10-01 13:04 UTC, KungA commented on Vostok.Hosting/Components/SystemMetrics/SystemMetricsBuilder.cs
> +            context.DisposableHostExtensions.Add(gcMonitor);
и тут

2021-10-05 08:56 UTC, KungA requested changes

2021-10-05 08:56 UTC, KungA commented on Vostok.Hosting/Components/Diagnostics/DiagnosticsBuilder.cs
> +        private static T AsDisposable<T>(BuildContext context, T disposable)
можно сразу в BuildContext этот метод вынести и юзать

и назвать RegisterDisposable

и тогда и весь список сделать приватным

2021-10-05 08:56 UTC, KungA commented on Vostok.Hosting/Components/BuildContext.cs
> +        public List<object> Disposables { get; set; }
логичней это поле сделать get-only notnull и всегда аппендить

2021-10-05 08:56 UTC, KungA commented on Vostok.Hosting/Components/BuildContext.cs
> +            var registeredExtensions = new HashSet<object>(ByReferenceEqualityComparer<object>.Instance);
```suggestion
            var registeredExtensions = new HashSet<object>(HostExtensions.GetAll().Select(p => p.Item2), ByReferenceEqualityComparer<object>.Instance);
```

2021-10-05 08:56 UTC, KungA commented on Vostok.Hosting/Components/SystemMetrics/SystemMetricsBuilder.cs
>              var gcMonitor = new GarbageCollectionMonitor();
```suggestion
            var gcMonitor = context.RegisterDisposable(new GarbageCollectionMonitor());
```

2021-10-07 05:59 UTC, HolyPrapor commented on Vostok.Hosting/Components/SystemMetrics/SystemMetricsBuilder.cs
>              var gcMonitor = new GarbageCollectionMonitor();
Конкретно в случае GarbageCollectionMonitor это неважно, но прям вот так писать не стоит, так как порядок диспоузов имеет значение.

В случае коллекторов ниже, нельзя сначала задиспоузить их, а потом подписки, потому что есть шанс что их попытаются использовать после диспоуза.

Чтобы было единообразно, везде буду диспоузить сначала подписки, а потом сами компоненты.

2021-10-08 08:42 UTC, kungasc approved these changes

2021-10-14 07:49 UTC, merged