Do not auto enable components if they were manually disabled
vostok/hosting pull request #94
Opened 2022-09-26 09:33 UTC by Ndker

resolve #88

2022-09-26 11:18 UTC, KungA requested changes

2022-09-26 11:18 UTC, kungasc commented on Vostok.Hosting.Tests/Components/Log/LogsBuilder_Tests.cs
> +
Не вижу тесты на случаи

1. Disable -> Enable
2. Setup -> Disable

мб ещё какие-то нужны для полноты

2022-09-26 11:18 UTC, kungasc commented on Vostok.Hosting/Components/Hercules/HerculesSinkBuilder.cs
> +            stateManager.Enable(false);
понятно что можно посмотреть на название флажка чтобы узнать что тут происходит

но кажется удобней читать код и вызывать будет если у нас будут разные методы (например AutoEnable и Enable)

2022-09-26 11:18 UTC, KungA commented on Vostok.Hosting.Tests/Components/Log/LogsBuilder_Tests.cs
> +        public void Should_not_auto_enable_file_log_when_manually_disabled()
вместо написания тестов на каждый компонент думаю будет достаточно написать их только для одного

а вот уже более тщательно все случаи потестить уже с ComponentStateManager

2022-09-26 11:18 UTC, KungA commented on Vostok.Hosting/Helpers/ComponentStateManager.cs
> +    internal class ComponentStateManager
я бы это и назвал ComponentState, а то что внутри например ComponentStateFlag

а то немного странно выглядят поля с таким типом в компонентах)

2022-09-26 14:01 UTC, Ndker commented on Vostok.Hosting.Tests/Components/Log/LogsBuilder_Tests.cs
> +
По первому пункту - там просто у билдеров логов нет явного метода Enable() в интерфейсах, например, в IVostokFileLogBuilder.  
Будем добавлять публичный метод для включения?  Или не просили - не надо?

2022-09-26 14:07 UTC, KungA commented on Vostok.Hosting.Tests/Components/Log/LogsBuilder_Tests.cs
> +
раньше получается вместо него был неявный выключатель

а раз мы его убираем, надо добавить получается

и придётся добавить отдельно заранее, чтобы люди смогли свой код поправить

(https://kontur.slack.com/archives/GCP8U9VEZ/p1664201149265849?thread_ts=1664184789.527029&cid=GCP8U9VEZ)

2022-09-27 08:35 UTC, Ndker commented on Vostok.Hosting.Tests/Components/Log/LogsBuilder_Tests.cs
> +
1. Disable -> Enable
2. Setup -> Disable

кейсы добавила, Всего 5 :

1. Setup =>  IsEnabled == true
2. Setup - Disable  =>  IsEnabled == false
3. Setup - Disable - Setup  => IsEnabled == false
4. Enable - Disable ->  IsEnabled == false
5. Setup - Disable - Enable => IsEnabled == true

2022-09-27 08:35 UTC, Ndker commented on Vostok.Hosting/Components/Hercules/HerculesSinkBuilder.cs
> +            stateManager.Enable(false);
Добавила так же отдельный метод

2022-09-27 08:36 UTC, Ndker commented on Vostok.Hosting.Tests/Components/Log/LogsBuilder_Tests.cs
> +        public void Should_not_auto_enable_file_log_when_manually_disabled()
Из LogBuilder убрала лишние тесты, создала отдельный ComponentState_Tests

2022-09-27 08:36 UTC, Ndker commented on Vostok.Hosting/Helpers/ComponentStateManager.cs
> +    internal class ComponentStateManager
Ну да, manager тут overkill

2022-09-27 13:35 UTC, KungA requested changes

2022-09-27 13:35 UTC, KungA commented on Vostok.Hosting.Tests/Components/Log/LogsBuilder_Tests.cs
> +    }
а где тестик на тот спорный случай с SetupConsoleLog()?

2022-09-27 13:35 UTC, KungA commented on Vostok.Hosting.Tests/Helpers/ComponentState_Tests.cs
> +        [Test]
а если совсем не трогали выключатель?

2022-09-27 13:35 UTC, KungA commented on Vostok.Hosting/Components/Environment/EnvironmentBuilder.cs
>          }
HerculesMetricEventSenderBuilder пропустила?

2022-09-27 13:35 UTC, KungA commented on Vostok.Hosting/Components/Environment/EnvironmentBuilder.cs
>          }
и HerculesServiceDiscoveryEventsSenderBuilder

2022-09-27 13:35 UTC, KungA commented on Vostok.Hosting/Components/Environment/EnvironmentBuilder.cs
>          }
и HerculesSpanSenderBuilder

2022-09-27 13:35 UTC, KungA commented on Vostok.Hosting/Components/Environment/EnvironmentBuilder.cs
>          }
не знаю кстати сходу, можно ли всё таки сделать базовый класс, и не копипастить 3 метода и поле стейта во все такие билдеры

2022-09-27 14:07 UTC, Ndker commented on Vostok.Hosting/Components/Environment/EnvironmentBuilder.cs
>          }
ого, да, пропустила их пачкой.  
Про базовый я думала изначально, но как-то не хотелось их жестко привязывать к одному родителю.
И еще при этом в Enable()/Disable() `return this` нужно возвращать. Хотя там наверное через дженерики можно. 

В принципе если мы считаем ок, что будет пачка internal Builder-ов, по контексту особо не связанных, а связанных только по наличию выключателя - то вроде да, можно сделать базовый, они сейчас от других классов не наследуются.

2022-09-27 14:09 UTC, KungA commented on Vostok.Hosting/Components/Environment/EnvironmentBuilder.cs
>          }
да, будет FileLogBuilder : Switchable<FileLogBuilder>

2022-09-27 14:13 UTC, kungasc commented on Vostok.Hosting/Components/Environment/EnvironmentBuilder.cs
>          }
но я не тестил, налезет ли интерфейс потом

если нет, то проще забить конечно

2022-09-27 18:52 UTC, Ndker commented on Vostok.Hosting.Tests/Components/Log/LogsBuilder_Tests.cs
> +    }
точно, добавила

2022-09-27 18:52 UTC, Ndker commented on Vostok.Hosting.Tests/Helpers/ComponentState_Tests.cs
> +        [Test]
+

2022-09-27 18:56 UTC, Ndker commented on Vostok.Hosting/Components/Environment/EnvironmentBuilder.cs
>          }
В итоге вот в таком стиле получилось:
```
SwitchableComponent<IVostokServiceBeaconBuilder>
```
в случае с `SwitchableComponent<ServiceBeaconBuilder>` - он не может увидеть, что у интерфейса `IVostokServiceBeaconBuilder` методы реализоны в этом базовом классе

2022-09-28 08:40 UTC, KungA approved these changes

2022-10-03 13:00 UTC, merged